on: 
  push:
    branches:
      - coverage

jobs:
    runs-on: ubuntu-latest

    steps:
   - name: Install dependencies
      run: |
        npm install

    - name: Run tests with coverage
      run: |
        npx jest --coverage